//
//  ClipboardHistory.swift
//  boringCode
//
//  Histórico do clipboard, como o Win+V do Windows: guarda o que você copia
//  (texto, links, imagens e arquivos) e, ao escolher um item, cola direto no app
//  da frente.
//
//  Como percebe uma cópia: o macOS não avisa, então a cada meio segundo compara
//  o `changeCount` do clipboard (um número, ler não mostra nada ao usuário).
//  Só quando ele muda o conteúdo é lido.
//
//  Permissão (macOS 15.4+): ler o clipboard de outro app sem você mandar colar
//  mostra um aviso do sistema. Sem o boringCode ligado em Privacidade e Segurança ›
//  "Colar de Outros Apps" seria um aviso a cada cópia, então só lemos com ele
//  ligado; até lá a aba explica e leva aos Ajustes. O primeiro pedido é sempre por
//  um clique seu (aba ou onboarding) — é ele que põe o boringCode na lista.
//
//  Privacidade: o que gerenciadores de senha marcam como sigiloso ou temporário
//  (padrão nspasteboard.org) nunca entra. O histórico fica só neste Mac, em
//  ~/Library/Application Support/boringCode/Clipboard (pasta só sua, 0700).
//

import AppKit
import Combine
import Defaults

@MainActor
final class ClipboardHistory: ObservableObject {
    static let shared = ClipboardHistory()

    enum Access: Equatable {
        /// Sem o aviso do macOS (antes do 15.4) ou ligado em "Colar de Outros Apps".
        case allowed
        /// O boringCode nunca pediu: um clique mostra o aviso do sistema.
        case notRequested
        /// Perguntando a cada vez ou negado: só muda nos Ajustes.
        case needsSettings
    }

    @Published private(set) var items: [ClipboardItem] = []
    @Published private(set) var access: Access = .allowed
    /// Pedido de acesso aberto (aviso do sistema na tela).
    @Published private(set) var isRequestingAccess = false

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var pollTimer: Timer?
    private var enabledCancellable: AnyCancellable?
    private var limitCancellable: AnyCancellable?
    private var saveTask: Task<Void, Never>?
    private var loaded = false

    /// Tipos que gerenciadores de senha e afins usam para pedir "não guarde isto".
    private static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
    ]
    private static let maxImageBytes = 25 * 1024 * 1024
    private static let maxRTFBytes = 512 * 1024
    private static let maxTextLength = 1_000_000

    private init() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    // MARK: - Ligar e desligar

    func start() {
        guard enabledCancellable == nil else { return }
        enabledCancellable = Defaults.publisher(.clipboardEnabled)
            .sink { [weak self] change in
                Task { @MainActor in self?.setRunning(change.newValue) }
            }
        limitCancellable = Defaults.publisher(.clipboardHistoryLimit, options: [])
            .sink { [weak self] _ in
                Task { @MainActor in self?.trimToLimit() }
            }
    }

    private func setRunning(_ running: Bool) {
        pollTimer?.invalidate()
        pollTimer = nil
        guard running else {
            if BoringViewCoordinator.shared.currentView == .clipboard {
                BoringViewCoordinator.shared.currentView = .home
            }
            return
        }
        loadIfNeeded()
        refreshAccess()
        // O que já estava copiado antes de abrir não conta como cópia nova.
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        pollTimer = timer
    }

    private func poll() {
        refreshAccess()
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard access == .allowed else { return }
        capture()
    }

    // MARK: - Permissão

    func refreshAccess() {
        let current: Access
        if #available(macOS 15.4, *) {
            switch pasteboard.accessBehavior {
            case .alwaysAllow: current = .allowed
            case .default: current = .notRequested
            default: current = .needsSettings
            }
        } else {
            current = .allowed
        }
        if current != access { access = current }
    }

    /// Mostra o aviso do sistema (uma leitura pedida pelo usuário). Se o acesso não
    /// ficar liberado de vez, abre os Ajustes no lugar certo.
    func requestAccess() async {
        refreshAccess()
        switch access {
        case .allowed:
            return
        case .needsSettings:
            openPrivacySettings()
            return
        case .notRequested:
            break
        }
        isRequestingAccess = true
        // A leitura espera a resposta do aviso: fora da thread principal o notch não trava.
        await Task.detached(priority: .userInitiated) {
            _ = NSPasteboard.general.types
            _ = NSPasteboard.general.string(forType: .string)
        }.value
        isRequestingAccess = false
        refreshAccess()
        if access != .allowed { openPrivacySettings() }
    }

    func openPrivacySettings() {
        if let url = URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Pasteboard") {
            NSWorkspace.shared.open(url)
        }
    }

    // MARK: - Captura

    private func capture() {
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard !types.isEmpty, types.isDisjoint(with: Self.privateTypes) else { return }

        let source = NSWorkspace.shared.frontmostApplication
        // Cópia feita pelo próprio boringCode (Shelf, perguntas dos agentes…): não é do usuário.
        if source?.processIdentifier == ProcessInfo.processInfo.processIdentifier { return }

        guard let item = readItem(types: types, source: source) else { return }
        insert(item)
    }

    private func readItem(types: Set<String>, source: NSRunningApplication?) -> ClipboardItem? {
        let bundleID = source?.bundleIdentifier
        let sourceName = source?.localizedName

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            let paths = urls.map(\.path)
            return ClipboardItem(
                id: UUID(), kind: .file, date: Date(),
                filePaths: paths, sourceBundleID: bundleID, sourceName: sourceName,
                fingerprint: ClipboardItem.fingerprint(kind: .file, Data(paths.joined(separator: "\n").utf8))
            )
        }

        let imageType: NSPasteboard.PasteboardType? = [.png, .tiff].first { types.contains($0.rawValue) }
        if let imageType, let data = pasteboard.data(forType: imageType), data.count <= Self.maxImageBytes {
            let fingerprint = ClipboardItem.fingerprint(kind: .image, data)
            if let existing = items.first(where: { $0.fingerprint == fingerprint }) {
                return existing
            }
            let id = UUID()
            let fileName = id.uuidString + (imageType == .png ? ".png" : ".tiff")
            guard ClipboardStorage.writeImage(data, named: fileName) else { return nil }
            return ClipboardItem(
                id: id, kind: .image, date: Date(),
                imageFile: fileName, imageType: imageType.rawValue,
                imagePixelSize: ClipboardStorage.pixelSize(of: data),
                sourceBundleID: bundleID, sourceName: sourceName,
                fingerprint: fingerprint
            )
        }

        if let string = pasteboard.string(forType: .string) {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty, string.count <= Self.maxTextLength else { return nil }
            let kind: ClipboardItem.Kind = Self.isLink(trimmed) ? .link : .text
            var rtf: Data?
            if kind == .text, let data = pasteboard.data(forType: .rtf), data.count <= Self.maxRTFBytes {
                rtf = data
            }
            return ClipboardItem(
                id: UUID(), kind: kind, date: Date(),
                text: string, rtf: rtf,
                sourceBundleID: bundleID, sourceName: sourceName,
                fingerprint: ClipboardItem.fingerprint(kind: kind, Data(string.utf8))
            )
        }

        if let url = pasteboard.string(forType: .URL), Self.isLink(url) {
            return ClipboardItem(
                id: UUID(), kind: .link, date: Date(),
                text: url, sourceBundleID: bundleID, sourceName: sourceName,
                fingerprint: ClipboardItem.fingerprint(kind: .link, Data(url.utf8))
            )
        }
        return nil
    }

    /// Um endereço sozinho (sem espaços), com esquema de web ou e-mail.
    static func isLink(_ string: String) -> Bool {
        guard !string.contains(where: \.isWhitespace), let url = URL(string: string),
              let scheme = url.scheme?.lowercased() else { return false }
        switch scheme {
        case "http", "https": return url.host?.isEmpty == false
        case "mailto", "ftp", "ssh": return true
        default: return false
        }
    }

    /// Item novo vai para o começo; o mesmo conteúdo copiado de novo sobe (sem repetir).
    private func insert(_ item: ClipboardItem) {
        var updated = items
        if let index = updated.firstIndex(where: { $0.fingerprint == item.fingerprint }) {
            var existing = updated.remove(at: index)
            existing.date = Date()
            existing.sourceBundleID = item.sourceBundleID ?? existing.sourceBundleID
            existing.sourceName = item.sourceName ?? existing.sourceName
            updated.insert(existing, at: 0)
        } else {
            updated.insert(item, at: 0)
        }
        items = updated
        trimToLimit()
        scheduleSave()
    }

    private func trimToLimit() {
        let limit = max(1, Defaults[.clipboardHistoryLimit])
        guard items.count > limit else { return }
        let removed = items[limit...]
        items.removeSubrange(limit...)
        removed.forEach(ClipboardStorage.deleteFiles(of:))
        scheduleSave()
    }

    // MARK: - Escolher, apagar

    /// Põe o item de volta no clipboard (do jeito que veio) e o sobe para o começo.
    func copyToPasteboard(_ item: ClipboardItem) {
        pasteboard.clearContents()
        switch item.kind {
        case .text:
            if let rtf = item.rtf { pasteboard.setData(rtf, forType: .rtf) }
            pasteboard.setString(item.text ?? "", forType: .string)
        case .link:
            pasteboard.setString(item.text ?? "", forType: .string)
            if let url = item.linkURL { pasteboard.setString(url.absoluteString, forType: .URL) }
        case .image:
            if let file = item.imageFile, let data = ClipboardStorage.imageData(named: file) {
                pasteboard.setData(data, forType: NSPasteboard.PasteboardType(item.imageType ?? NSPasteboard.PasteboardType.png.rawValue))
            }
        case .file:
            pasteboard.writeObjects(item.fileURLs as [NSURL])
        }
        // Nossa própria escrita não vira cópia nova.
        lastChangeCount = pasteboard.changeCount

        if let index = items.firstIndex(where: { $0.id == item.id }) {
            var moved = items.remove(at: index)
            moved.date = Date()
            items.insert(moved, at: 0)
            scheduleSave()
        }
    }

    /// Dá para colar sozinho? Precisa do ajuste ligado e da Acessibilidade do helper.
    func canPaste() async -> Bool {
        guard Defaults[.clipboardPasteOnSelect] else { return false }
        return await XPCHelperClient.shared.isAccessibilityAuthorized()
    }

    /// Aperta ⌘V pelo helper (o item já tem que estar no clipboard).
    /// - Parameter targetPID: app que recebe o ⌘V quando o notch está com o teclado
    ///   (busca em uso); nil manda para quem estiver na frente.
    func sendPaste(targetPID: pid_t?) async -> Bool {
        // O notch fecha primeiro e o app de destino volta a receber o teclado.
        try? await Task.sleep(for: .milliseconds(120))
        return await XPCHelperClient.shared.pasteCommandV(toPID: targetPID ?? 0)
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        ClipboardStorage.deleteFiles(of: item)
        scheduleSave()
    }

    func clear() {
        items.forEach(ClipboardStorage.deleteFiles(of:))
        items = []
        scheduleSave()
    }

    // MARK: - Disco

    private func loadIfNeeded() {
        guard !loaded else { return }
        loaded = true
        items = ClipboardStorage.load()
        trimToLimit()
    }

    private func scheduleSave() {
        saveTask?.cancel()
        let snapshot = items
        saveTask = Task {
            try? await Task.sleep(for: .seconds(1))
            guard !Task.isCancelled else { return }
            await Task.detached(priority: .utility) { ClipboardStorage.save(snapshot) }.value
        }
    }
}

/// Pasta do histórico: o índice (JSON) e as imagens.
enum ClipboardStorage {
    static let directory: URL = {
        let support = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? FileManager.default.temporaryDirectory
        return support.appendingPathComponent("boringCode/Clipboard", isDirectory: true)
    }()
    private static var imagesDirectory: URL { directory.appendingPathComponent("images", isDirectory: true) }
    private static var indexURL: URL { directory.appendingPathComponent("history.json") }

    private static func ensureDirectories() {
        let fileManager = FileManager.default
        for url in [directory, imagesDirectory] where !fileManager.fileExists(atPath: url.path) {
            try? fileManager.createDirectory(at: url, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
        }
    }

    static func load() -> [ClipboardItem] {
        guard let data = try? Data(contentsOf: indexURL),
              let items = try? JSONDecoder().decode([ClipboardItem].self, from: data) else { return [] }
        // Imagem que sumiu da pasta não volta como cartão vazio.
        return items.filter { item in
            guard item.kind == .image, let file = item.imageFile else { return true }
            return FileManager.default.fileExists(atPath: imageURL(named: file).path)
        }
    }

    static func save(_ items: [ClipboardItem]) {
        ensureDirectories()
        guard let data = try? JSONEncoder().encode(items) else { return }
        try? data.write(to: indexURL, options: [.atomic])
        try? FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: indexURL.path)
    }

    static func imageURL(named name: String) -> URL { imagesDirectory.appendingPathComponent(name) }

    static func writeImage(_ data: Data, named name: String) -> Bool {
        ensureDirectories()
        return (try? data.write(to: imageURL(named: name), options: [.atomic])) != nil
    }

    static func imageData(named name: String) -> Data? {
        try? Data(contentsOf: imageURL(named: name))
    }

    static func deleteFiles(of item: ClipboardItem) {
        guard let file = item.imageFile else { return }
        try? FileManager.default.removeItem(at: imageURL(named: file))
    }

    // NSCache é seguro entre threads; o Swift só não sabe disso.
    nonisolated(unsafe) private static let thumbnails = NSCache<NSString, CGImage>()

    /// Imagem reduzida para o cartão (lê só o necessário do arquivo, com a rotação certa).
    static func thumbnail(at url: URL, maxPixelSize: Int) -> CGImage? {
        if let cached = thumbnails.object(forKey: url.path as NSString) { return cached }
        guard let source = CGImageSourceCreateWithURL(url as CFURL, nil) else { return nil }
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: maxPixelSize,
        ]
        guard let image = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else { return nil }
        thumbnails.setObject(image, forKey: url.path as NSString)
        return image
    }

    static func pixelSize(of data: Data) -> CGSize? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let width = properties[kCGImagePropertyPixelWidth] as? Int,
              let height = properties[kCGImagePropertyPixelHeight] as? Int else { return nil }
        return CGSize(width: width, height: height)
    }
}
